basePath: /v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a Veggie application.
  title: Veggie API
  version: "1.0"
paths:
  /users:
    post:
      description: Tạo Tài Khoản Bằng Email
      produces:
      - application/json
      responses:
        "200":
          description: Created Successfully
          schema:
            type: string
      summary: Tạo Tài Khoản
      tags:
      - users
swagger: "2.0"
