definitions:
  gin.CurrencyCreationResponse:
    properties:
      message:
        type: string
    type: object
  gin.DeleteUserByIdResponse:
    properties:
      message:
        type: string
    type: object
  gin.FindListUsersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.UserType'
        type: array
    type: object
  gin.FindUserByIdResponse:
    properties:
      data:
        $ref: '#/definitions/model.UserType'
    type: object
  gin.LoginResponse:
    properties:
      data:
        $ref: '#/definitions/model.UserResponse'
      token:
        type: string
    type: object
  gin.UserCreationResponse:
    properties:
      message:
        type: string
    type: object
  model.CategoryCreationType:
    properties:
      category_name:
        type: string
      description:
        type: string
    type: object
  model.CurrencyCreationType:
    properties:
      currency_code:
        type: string
      currency_name:
        type: string
      exchange_rate:
        type: number
    required:
    - currency_code
    - currency_name
    type: object
  model.LoginInput:
    properties:
      password:
        type: string
      user_name:
        type: string
    required:
    - password
    - user_name
    type: object
  model.ProductCreationType:
    properties:
      description:
        type: string
      dph:
        type: integer
      image_url:
        type: string
      product_code:
        type: string
      product_name_eng:
        type: string
      product_name_vn:
        type: string
    required:
    - product_code
    - product_name_eng
    - product_name_vn
    type: object
  model.SupplierCreationType:
    properties:
      currencyID:
        type: string
      description:
        type: string
      supplier_name:
        type: string
      tax_id:
        type: string
    required:
    - supplier_name
    - tax_id
    type: object
  model.UserCreationType:
    properties:
      email:
        type: string
      password:
        type: string
      user_name:
        type: string
    required:
    - email
    - password
    - user_name
    type: object
  model.UserResponse:
    properties:
      email:
        type: string
      status:
        type: string
      user_id:
        type: string
      user_name:
        type: string
    type: object
  model.UserType:
    properties:
      created_at:
        type: string
      status:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
  description: Đây là tài liệu API cho ứng dụng Hệ Thống Veggie
  title: Veggie API
  version: "1.0"
paths:
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Đăng Nhập tài khoản mới bằng email
      parameters:
      - description: User data
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/model.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: Đăng Nhập Tài Khoản Thành Công
          schema:
            $ref: '#/definitions/gin.LoginResponse'
      summary: Đăng Nhập Tài Khoản
      tags:
      - Authorization
  /v1/categories:
    post:
      consumes:
      - application/json
      description: Tạo Nhóm Sản Phẩm
      parameters:
      - description: category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.CategoryCreationType'
      produces:
      - application/json
      responses:
        "200":
          description: Tạo Nhóm Sản Phẩm Thành Công
          schema:
            $ref: '#/definitions/gin.UserCreationResponse'
      security:
      - BearerAuth: []
      summary: Tạo Nhóm Sản Phẩm
      tags:
      - Nhóm Sản Phẩm
  /v1/currencies:
    post:
      consumes:
      - application/json
      description: Tạo Tiền Tệ mới
      parameters:
      - description: Curency data
        in: body
        name: currency
        required: true
        schema:
          $ref: '#/definitions/model.CurrencyCreationType'
      produces:
      - application/json
      responses:
        "200":
          description: Tạo Tiền Tệ Thành Công
          schema:
            $ref: '#/definitions/gin.CurrencyCreationResponse'
      summary: Tạo Tiền Tệ
      tags:
      - Tiền Tệ
  /v1/products:
    post:
      consumes:
      - application/json
      description: Tạo Sản Phẩm Mới
      parameters:
      - description: product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.ProductCreationType'
      produces:
      - application/json
      responses:
        "200":
          description: Tạo Tài Khoản Thành Công
          schema:
            $ref: '#/definitions/gin.UserCreationResponse'
      security:
      - BearerAuth: []
      summary: Tạo Sản Phẩm
      tags:
      - Sản Phẩm
  /v1/supplier:
    post:
      consumes:
      - application/json
      description: Tạo Nhà Cung Cấp
      parameters:
      - description: supplier
        in: body
        name: supplier
        required: true
        schema:
          $ref: '#/definitions/model.SupplierCreationType'
      produces:
      - application/json
      responses:
        "200":
          description: Tạo Nhà Cung Cấp Thành Công
          schema:
            $ref: '#/definitions/gin.UserCreationResponse'
      security:
      - BearerAuth: []
      summary: Tạo Nhà Cung Cấp
      tags:
      - Nhà Cung Cấp
  /v1/users:
    get:
      consumes:
      - application/json
      description: Lấy danh sách tài khoản
      produces:
      - application/json
      responses:
        "200":
          description: Lấy danh sách tài khoản Thành Công
          schema:
            $ref: '#/definitions/gin.FindListUsersResponse'
      security:
      - BearerAuth: []
      summary: Lấy danh sách tài khoản
      tags:
      - Tài Khoản
    post:
      consumes:
      - application/json
      description: Tạo tài khoản mới bằng email
      parameters:
      - description: User data
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/model.UserCreationType'
      produces:
      - application/json
      responses:
        "200":
          description: Tạo Tài Khoản Thành Công
          schema:
            $ref: '#/definitions/gin.UserCreationResponse'
      summary: Tạo Tài Khoản
      tags:
      - Authorization
  /v1/users/:{id}:
    delete:
      consumes:
      - application/json
      description: Xóa tài khoản theo id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Xóa tài khoản theo id Thành Công
          schema:
            $ref: '#/definitions/gin.DeleteUserByIdResponse'
      security:
      - BearerAuth: []
      summary: Xóa tài khoản theo id
      tags:
      - Tài Khoản
    put:
      consumes:
      - application/json
      description: Lấy tài khoản theo id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lấy tài khoản theo id Thành Công
          schema:
            $ref: '#/definitions/gin.FindUserByIdResponse'
      security:
      - BearerAuth: []
      summary: Lấy tài khoản theo id
      tags:
      - Tài Khoản
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
